//package lingo;
package com.solocoding.lingo; 

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author guero
 */
public class MainFrame extends javax.swing.JFrame {
//     public MainFrame(JScrollPane scroll){
//         initComponents();
//     }

    private int x = 600;    
    private int y = 500;    

    public MainFrame() {
        initComponents();
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame(JPanel pan) {
        
        initComponents();
        ///JPanel pan = pan; 
        
        JScrollPane scroll = new JScrollPane(pan);
        
        int x = scroll.getSize().height;        
        int y = scroll.getSize().width;
        Dimension dem = pan.getSize(); /// new Dimension(x,y);

        scroll.setPreferredSize(new Dimension(x, y));
        ///scroll.get
        /// scroll.setPreferredSize(new Dimension(1100, 800));
//         
        setContentPane(scroll);
//
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack(); // Automatically resize the frame to fit the content
        setLocationRelativeTo(null); // Center the frame on the screen
        setVisible(true);
       // this.setResizable(false);
        
    }

    public void frameSizeSetters(int x, int y) {
        this.x = x;        
        this.y = y;        
        
    }
//    public void ySetter(int y){
//        this.y= y; 
//    
//    }

    public void updateFramSize(JPanel pan) {
        JScrollPane scroll = new JScrollPane(pan);
        System.err.println("x: " + x + "y: " + y);
        scroll.setPreferredSize(new Dimension(x, y));        
        setContentPane(scroll);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public void changeView(JPanel pan) {
        JScrollPane scroll = new JScrollPane(pan);
        scroll.setPreferredSize(new Dimension(600, 500));        
        setContentPane(scroll);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public void changeViewTable(JPanel pan) {
        JScrollPane scroll = new JScrollPane(pan);
        scroll.setPreferredSize(new Dimension(1200, 800));        
        setContentPane(scroll);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public void setPanel(JPanel pan) {
        ///this.panel = pan;
//        add(panel);
//         JScrollPane scroll = new JScrollPane(pan);
//        //scroll.setVisible(true);
//        setContentPane(scroll);
//        setSize(800, 400);
//       setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//       scroll.setVisible(rootPaneCheckingEnabled);
//        this.setVisible(rootPaneCheckingEnabled);

///this.setContentPane(pan);
        /// return this.panel; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                /// new MainFrame(scroll).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
